#!/bin/bash

p="p"
n_riga=$(($RANDOM % 307 + 1))

mac0=$(sed -n $n_riga'p' /home/chris/Documents/scripting_sh/indirizzi.txt)

mac1=${mac0:0:2}":"${mac0:2:2}":"${mac0:4:2}":" 


lettere=("A" "B" "C" "D" "E" "F")

array=()

for i in 0 1 3 5 
do
array[i]=$(($RANDOM % 10))
done

for i in 2 4
do
r=$(($RANDOM % 6))
array[i]=${lettere[$r]}
done

finale=${array[@]:0:2}":"${array[@]:2:2}":"${array[@]:4:2}

finale=$(echo "$finale" | sed 's/ //g')

ifconfig wlo1 down

echo "Indirizzo MAC prima:"
ip link show wlo1
ip link set dev wlo1 address1 $mac1$finale

ifconfig wlo1 up
echo "Indirizzo MAC dopo:"
ip link show wlo1
